@startwbs
* うつ病について

** 自己紹介
*** 一般的な自己紹介
*** 病歴紹介
*** 現在の私

** 30 年の間に得られた知見
*** うつ病とは何か
**** 患者視点
***** うつ病とは病気である
****** それ以上でもそれ以下でもない
****** 他の疾患同様治療対象
****** 残念ながら自分は治療を要する一患者
****** 合理的に治療に取り組まないと人生詰む
***** どんな病気か
****** 最悪死亡する
****** 障害者になることも
****** 自己コントロールをロストするから
******* これが一番怖い
******* 普通のときは考えないことを考える
******* 病気で以下が障害される
******** 思考力
******** 判断力
******** 感情
******* なので自分の思考、判断、感情を信じるのは危険
******* 自分が急性期なのかそうでないのか自分では判断できない
******* 医療を頼ろう
******* 合理的に治療に取り組もう
***** 母性的集団
****** 私を分かって？可哀そうな私？
****** 残念ながら治るのに役立たない
****** 母性的集団を求めてしまう性向
******* 気持はわかる
******* 一時的な休憩場所なら
******* でも居着くと有害
******* 母性的集団の構成
******** 母性を求める患者
********* <b>理解</b>されたいと言う
********** 理解って何？優しくされること？
********** まるで乳幼児の欲求ように思いませんか？
********** さっさと卒業したほうがいいのでは？
******** 母性を提供する共依存イネイブラー
********* 実はイネイブラーには相手への理解も愛情もない
********* 困った問題のある人を助ける自分が愛おしい
********* 病者が回復していくと自分の存在意義を見失う
********** 病者の回復を無意識に妨害しはじめる
******** どちらも勘違いしてはいけない
********* どちらにも相手に対する愛情も心配も思いやりもまったく無い
********* 歪んだ自己愛集団に過ぎない
********* 人間の持つ愛情などでは決してない
******** そんな集団のメンバーになってはいけない
********* 治るのが遠のく。あるいは永遠にやってこない
********* イネイブラーの共依存も悪化する
********* どちらにも良くない
******** 正しい自己認識が非常に重要
******* 休憩し終えたらさっさと離れるのがお互いのため
****** 本当の理解者とは
******* 当事者の様子がおかしな時にそれを指摘してくれる
******* 受診を勧めてくれる
******* 睡眠環境を調整してくれる
******* 入院を勧めてくれる
******* 当事者の状況によっては当事者を病院に連れて行き医療保護入院の手続きをしてくれる
******** 急性期の当事者の思考力、判断力、感情が障害されているから
******** 当事者に病識が無い場合も
******[#orange] 一人の人間として自立しましょう
*******[#orange] 自分自身を救う主役は他ならぬ自分自身です
******* でも助けをくれる人の支援はありがたく受けましょう
******** 医師、看護師、臨床心理士、ケースワーカー、国、役所、教員、家族etc
******** 生きていく助けになります！！
******* 良くなる妨げになる人との距離感をどうするのか考えましょう

**** 医学から見たうつ病 (要監修)
'***** モノアミン仮説
'***** 神経炎症仮説
'***** 神経可逆性仮説
'***** コルチゾール仮説
'***** その他
***** <img src="fig2025031701.svg">

*** うつ病の治療方法 (要監修)

**** 薬物療法
***** <img src="fig2025031803.svg">
***** 再発や再増悪防止のための維持療法も

**** 非薬物療法 (要監修)
***** 電気けいれん療法
***** 反復経頭磁気刺激療法

***** 運動療法
****** 高強度インターバル・トレーニング
****** 持久力持続トレーニング

***** 温熱療法 (研究途上)
****** サウナ療法
****** 入浴療法

***** 心理療法
****** 診察室などで行われる言語的介入
****** 認知行動療法
******* 評価と治療方針決定
******* プロトコルに従って実施
******* エクスプレッシブ・ライティング
******* メタ認知
******* SST (ソーシャル・スキル・トレーニング : 社会技能訓練)
******* アサーション
******* その他
****** その他

*****[#orange] セルフケア
******[#orange] 始める前に
*******[#orange] あわてないこと
*******[#orange] あせらないこと
*******[#orange] できない時期はどうしてもある
******[#orange] 生活習慣
*******[#orange] 早寝早起き
*******[#orange] アルコールを避ける
*******[#orange] 煙草を避ける
*******[#orange] カフェインの制限
*******[#orange] 十分な睡眠
*******[#orange] 日光を十分浴びる

******[#orange] 運動療法
******* 高強度インターバル・トレーニング
******* 持久力持続トレーニング
*******[#orange] ウォーキング
********[#orange] 散歩
********[#orange] ハイキング
********[#orange] フォトウォーク
********[#orange] バードウォッチング
********[#orange] 自然観察
*******[#orange] サイクリング
*******[#orange] 登山
*******[#orange] スイミング
*******[#orange] その他

******[#orange] リラクゼーション
*******[#orange] 入浴
********[#orange] お風呂
********[#orange] 温泉
********[#orange] サウナ
*******[#orange] マインドフルネス
*******[#orange] 座禅

******[#orange] エクスプレッシブ・ライティング
*******[#orange] 目的
********[#orange] 自分の感情、思考、判断
*********[#orange] 見える化
*********[#orange] 客観化
*********[#orange] 多角化
********[#orange] PDSA サイクルのように
*******[#orange] 日記
*******[#orange] メモ習慣
*******[#orange] CBT コラム法
********[#orange] トリプルコラム法
********[#orange] 突っ込みノート法
*******[#orange] ジャーナリング
*******[#orange] メタ認知トレーニング
*******[#orange] その他

******[#orange] レクリエーション
*******[#orange] 音楽
*******[#orange] 読書
*******[#orange] 旅行
*******[#orange] 日帰り旅行
*******[#orange] 各種レジャー

****** その他
******[#red] <color:white>注意を要するもの</color>
*******[#red] <color:white>SNS</color>
*******[#red] <color:white>動画サイト</color>
*******[#red] <color:white>ネガティブなフィードバックが多過ぎる</color>
*******[#red] <color:white>害を減らす工夫をしないと危険</color>

*******[#orange] 実は健康な人たちにとっても気をつけないと健康上のリスク
********[#orange] 報酬系を過剰に刺激するシステム上の仕組み
*********[#orange] 集客のため
*********[#orange] 依存症製造マシーン化している
********[#orange] 怒りの感情を増幅させる設計
*********[#orange] 相容れない考えにネガティブに反応してしまう人間の習性を利用している
*********[#orange] 相容れない考えが世の中に溢れているのは当たり前だけど人はそれを忘れる
*********[#orange] それを利用して滞在時間を増やす設計になっている
*********[#orange] 元エンジニアとしてかなり悪質なシステムだと評したい

********[#orange] 問題設計リスト
*********[#orange] 文字数制限
**********[#orange] 誤解、誤読の源泉
**********[#orange] 人から読解能力を奪う設計
**********[#orange] 人から文書作成能力を奪う設計
*********[#orange] コメント機能
**********[#orange] 対立の源泉
*********[#orange] お勧め機能
**********[#orange] 生活圏に関係のない刺激を無理矢理捩じ込む
*********[#orange] 再ポスト機能
**********[#orange] 対立の源泉
*********[#orange] コメント付き再ポスト機能
**********[#orange] 対立の源泉
*********[#orange] 検索機能
**********[#orange] 他人の意見が気になる人間の性質を利用
**********[#orange] 生活圏に関係のない刺激を無理矢理捩じ込む
********[#orange] インフルエンサーの問題
*********[#orange] 煽ることで閲覧数を増やそうとする
**********[#orange] お金のため
**********[#orange] 過剰な承認欲求
********[#orange] 運営会社の問題
*********[#orange] 自社の経済的利益のために人の健康を害する人の性質をフル活用
*********[#orange] 世に問題を問おうとすると、表現の自由を盾にする悪質さ
*********[#orange] 既存メディアなら避けるネガティブ・キャンペーンを平気でやる
*********[#orange] 運用時の行き過ぎた言論統制
********[#orange] 病人製造機だと元 IT エンジニアとして断言する
********[#orange] 何を言っても改善されないので利用にはしたたかさが絶対に必要
@endwbs
