@startmindmap
<style>
mindmapDiagram {
  node {
    BackgroundColor lightGray
  }
  boxless {
    FontColor darkgreen
  }
}
</style>
* Daycare メンバに\n遺したいこと
** 自己紹介
*** 一般的な自己紹介
*** 病歴紹介
*** 現在の私
** 得られた知見
*** うつ病とは何か
**** 患者視点
***** うつ病とは\n病気である
****** それ以上でも\nそれ以下でもない
****** 他の疾患同様\n治療対象
****** 残念ながら\n自分は治療を\n要する一患者
****** 合理的に治療に\n取り組まないと\n人生詰む
***** どんな病気か
****** 最悪死亡する
****** 障害者になることも
****** 自己コントロールを\nロストするから
******* これが一番怖い
******* 普通のときは\n考えないことを\n考える
******* 病気で以下が\n障害される
******** 思考力
******** 判断力
******** 感情
******* なので自分の\n思考、判断、感情を\n信じるのは危険
******* 自分が急性期なのか\nそうでないのか\n自分では判断できない
******* 医療を頼ろう
******* 合理的に\n治療に取り組もう
***** 私を分かって？\n可哀そうな私？
****** 残念ながら\n治るのに役立たない
****** 母性的集団を求めてしまう性向
******* 気持はわかる
******* 一時的な休憩場所なら
******* でも居着くと有害
******* 母性的集団の構成
******** 母性を求める患者
********* 理解されたいと言う
******** 母性を提供する\n共依存イネイブラー
********* イネイブラーには\n相手への\n理解も愛もない
********* 病者を助ける\n自分が愛おしい
********* 病者が回復していくと\n自分の存在意義を見失う
********** 病者の回復を\n無意識に\n妨害しはじめる
******** どちらも勘違いしては\nいけない
******** どちらにも相手に対する\n愛情も\n心配も\n思いやりも\n全てがまったく無い
******** 歪んだ自己愛\n集団に過ぎない
******** 人間の愛などでは\n決してない
******** そんな集団の\nメンバーになっては\nいけない
********* 治るのが遠のく\nあるいは永遠に\nやってこない
********* イネイブラーの\n共依存も悪化する
********* どちらにも\n良くない
******** どちらも勘違いしては\nいけない
******* 休憩し終えたら\nさっさと離れるのが\n自分と相手のため
****** 本当の理解者とは
******* 当事者の様子がおかしな時に\nそれを指摘してくれる
******* 睡眠環境を調整してくれる
******* 受診を勧めてくれる
******* 入院を勧めてくれる
******* 当事者の状況によっては\n当事者を病院に連れて行き\n医療保護入院の手続きをしてくれる
******** 急性期の当事者の\n思考力、判断力、感情が\n障害されているから
******** 当事者に病識が無い場合も
**** 医学から見たうつ病\n(要監修)
***** モノアミン仮説
***** 神経炎症仮説
***** 神経可逆性仮説
***** コルチゾール仮説
***** その他
*** うつ病の治療方法\n(要監修)
**** 薬物療法
***** SSRI などの抗うつ薬
***** リチウム\n(増強療法)
***** 第 2 世代抗精神病薬\n(増強療法)
***** ADHD 用の薬\n(増強療法)
***** もちろんうつ病適用
***** 再発や再増悪防止の\nための維持療法も
**** 非薬物療法
***** 電気けいれん療法
***** 反復経頭磁気刺激療法
***** 運動療法
****** 高強度インターバル・トレーニング
****** 持久力持続トレーニング
***** 温熱療法\n(エビデンスが不十分)
****** サウナ療法
****** 入浴療法
***** 心理療法
****** 診察室などで行われる言語的介入
****** 認知行動療法
******* 評価と治療方針決定
******* プロトコルに従って実施
******* メタ認知
******* SST (ソーシャル・スキル・トレーニング : 社会技能訓練)
******* アサーション
******* その他
****** マインドフルネス
****** その他
***** セルフケア
******[#orange] 生活習慣
*******[#orange] 早寝早起き
*******[#orange] アルコールを避ける
*******[#orange] 煙草を避ける
*******[#orange] カフェインの制限
*******[#orange] 十分な睡眠
*******[#orange] 日光を十分浴びる
******[#orange] 運動療法
******* 高強度インターバル・トレーニング
******* 持久力持続トレーニング
*******[#orange] 散歩
****** 温熱療法\n(エビデンスが不十分)
******* サウナ療法
******* 入浴療法
****** マインドフルネス
******[#orange] リラクゼーション
*******[#orange] 運動
********[#orange] 散歩
********[#orange] サイクリング
********[#orange] ハイキング
********[#orange] スイミング
********[#orange] その他
*******[#orange] 入浴
********[#orange] お風呂
********[#orange] 温泉
*******[#orange] マインドフルネス
*******[#orange] レクリエーション
********[#orange] 音楽
********[#orange] 読書
********[#orange] 旅行
********[#orange] 日帰り旅行
********[#orange] 各種レジャー
****** その他
******[#red] <color:white>注意を要するもの</color>
*******[#red] <color:white>SNS</color>
*******[#red] <color:white>動画サイト</color>
*******[#red] <color:white>ネガティブなフィードバックが多過ぎる</color>
*******[#red] <color:white>害を減らす工夫をしないと危険</color>
*******[#orange] 実は健康な人たちにとっても\n気をつけないと健康上のリスク
********[#orange] 報酬系を過剰に刺激する\nシステム上の仕組み
*********[#orange] 集客のため
*********[#orange] 依存症製造マシーン化している
********[#orange] 怒りの感情を増幅させる設計
*********[#orange] 相容れない考えにネガティブに反応してしまう\n人間の習性を利用している
*********[#orange] 相容れない考えが世の中に溢れているのは\n当たり前だけど人はそれを忘れる
*********[#orange] それを利用して滞在時間を増やす設計になっている
*********[#orange] 1 元エンジニアとして\n悪質なシステムだと評したい
********[#orange] 問題設計リスト
*********[#orange] 文字数制限
**********[#orange] 誤解、誤読の源泉
*********[#orange] コメント機能
**********[#orange] 対立の源泉
*********[#orange] お勧め機能
**********[#orange] 生活圏に関係のない刺激を無理矢理捩じ込む
*********[#orange] 再ポスト機能
**********[#orange] 対立の源泉
*********[#orange] コメント付き再ポスト機能
**********[#orange] 対立の源泉
*********[#orange] 検索機能
**********[#orange] 他人の意見が気になる人間の性質を利用
**********[#orange] 生活圏に関係のない刺激を無理矢理捩じ込む
********[#orange] インフルエンサーの問題
*********[#orange] 煽ることで閲覧数を増やそうとする
**********[#orange] 金のため
**********[#orange] 過剰な承認欲求
********[#orange] 運営会社の問題
*********[#orange] 自社利益のために人の健康に有害な人の性質をフル利用
*********[#orange] 問題を問おうとすると表現の自由を盾にする悪質さ
*********[#orange] 既存メディアなら避けるネガティブ・キャンペーンを平気でやる
*********[#orange] 運用時の行き過ぎた言論統制
********[#orange] 病人製造機だと元 IT エンジニアとして断言する
********[#orange] 何を言っても改善されないので利用にはしたたかさが絶対に必要
@endmindmap
