@startwbs
<style>
wbsDiagram {
  :depth(0) {
    BackgroundColor transparent
    LineColor transparent
    FontColor transparent
  }
}
</style>
'!pragma layout elk
* root
**[#lightgreen]:<b>うつ病歴 30 年当事者の知見</b>
<b>レジュメ設計書</b>;

*** 注意事項
**** 病気や障害、治療の話が中心となります
***** 以下のことがあるかも
****** 感情的動揺
****** つらい思い出のフラッシュバック
****** 病状の悪化
**** 以下の場合は見るのを止めてください
***** 医療スタッフに止められている
***** 病状がよくない
***** 病状が悪化してきた
****** 聞いていて気分が悪くなっってきた
****** 感情動きが激しくなって制御が困難になりつつある
****** その他自身の病状が悪化してきた
****** しんどくなってきた
****[#orange] しんどいのを無理しては絶対にいけません
*****[#orange] しんどいのは治療場面に限定しましょう
****** ex)\n認知行動療法\nSST
****** 実生活もしんどいものですが

*** 自己紹介
**** 一般的な自己紹介
**** 病歴紹介
**** 現在の私

*** うつ病とは何か

**** 医学から見たうつ病
***** <img src="fig2025031701.svg">

**** 患者視点
*****[#red] <color:white><b>うつ病とは病気である</b></color>
****** それ以上でもそれ以下でもない
****** 他の疾患同様治療対象
****** 合理的に治療に取り組まないと人生詰む

***** どんな病気か
****** 他の病気と同じく気がつくとなってしまっている
******[#red] <color:white><b>最悪死亡する</b></color>
****** 障害者になることも

******[#red] <color:white><b>自己コントロールをロストする</b></color>
******* これが一番怖い
******* 普通のときは考えないことを考える
*******[#red] <color:white><b>病気で以下が障害される</b></color>
********[#red] <color:white><b>思考力</b></color>
********[#red] <color:white><b>判断力</b></color>
********[#red] <color:white><b>感情</b></color>
*******[#red] <color:white><b>なので自分の思考、判断、感情を信じるのは危険</b></color>
******* 自分が急性期なのかそうでないのか自分では判断できない
******** 病識を持てない場合も多い
******** 家族などの身近な人の助けがとても重要
********* 医療に結びつけて！！
********* 病状によっては医療保護入院も視野に入れて
******** 身近な人の言うことに従いましょう
*******[#red] <color:white><b>医療を頼ろう</b></color>
*******[#red] <color:white><b>合理的に治療に取り組もう</b></color>

*** うつ病の治療方法

**** 医療介入
***** 薬物療法
****** <img src="fig2025031803.svg">
****** 再発や再増悪防止のための維持療法も

***** 非薬物療法
****** 電気けいれん療法
****** 反復経頭磁気刺激療法

****** 運動療法
******* 高強度インターバル・トレーニング
******* 持久力持続トレーニング

****** 温熱療法 (研究途上)
******* サウナ療法
******* 入浴療法

****** 心理療法
******* 診察室などで行われる言語的介入
******* 認知行動療法 (CBT)
'******** 評価と治療方針決定
'******** プロトコルに従って実施
'******** エクスプレッシブ・ライティング
'******** メタ認知
'******** SST (ソーシャル・スキル・トレーニング : 社会技能訓練)
'******** アサーション
'******** その他
******* その他

****[#ffc993] セルフケア
*****[#ffc993] 目的
******[#ffc993] ストレスの緩和
******* リラクゼーション
******* 洞察と理解
******** 自己
******** 人間
******** 世の中
******* 多様性への理解
******* 共感と許し(許容・受容)


*****[#ffc993] 始める前に
******[#ffc993] ライフワークにならざるを得ない
******[#ffc993] あわてないこと
******[#ffc993] あせらないこと
******[#ffc993] できない時期はどうしてもある

*****[#ffc993] 生活習慣
******[#ffc993] 早寝早起き
******[#ffc993] アルコールを避ける
******[#ffc993] 煙草を避ける
******[#ffc993] カフェインの制限
******[#ffc993] 十分な睡眠
******[#ffc993] 日光を十分浴びる

*****[#ffc993] 運動療法
****** 高強度インターバル・トレーニング
****** 持久力持続トレーニング
****** ウォーキング
******* 散歩
******* ハイキング
******* フォトウォーク
******* バードウォッチング
******* 自然観察
****** サイクリング
****** 登山
****** スイミング
****** その他

*****[#ffc993] リラクゼーション
****** 入浴
******* お風呂
******* 温泉
******* サウナ
****** マインドフルネス
****** 座禅

*****[#ffc993] レクリエーション
****** 音楽
****** 読書
****** 旅行
****** 日帰り旅行
****** 各種レジャー

*****[#ffc993] 記録
******[#ffc993] 目的
*******[#ffc993] 自分の感情、思考、判断
********[#ffc993] 見える化
********[#ffc993] 客観化
********[#ffc993] 多角化
*******[#ffc993] PDSA サイクルのように

******[#ffc993] 方法
******* 日記
******* メモ習慣
******* バレットジャーナル
******* ジャーナリング
******* 非公開ホームページ
******* CBT コラム法
******** トリプルコラム法
******** 突っ込みノート法
******* その他

****[#orange] 治療に臨むに当って助けになることなったこと
*****[#orange] 自分を治療対象として認識する
*****[#orange] エビデンスに基く医学情報
*****[#orange] 治療メニューの意味理解
*****[#orange]:　　　 <b>状態把握の用語変換</b>
　　　 <color:red><b>極力精神医学用語に</b></color>
====
ex) 死にたい
　　　⇩
　　希死念慮が生じている
　　　　死にたいという表現は
　　　　情動の強度を伝えるための
　　　　<b>補助表現に格下げする</b>;
******[#orange] ロストコントロール対策

*****[#ffc993] 好奇心
******[#ffc993] 様々な学び
******* 精神医学
******* 心理学
******** 認知行動療法 (CBT)
******** 精神分析
******** 実存分析
******** 人間性心理学(マズローとか)
******** その他
******* 自然科学
******* 哲学
******* 宗教
******* 統計学
******* 様々なライフハック

*****[#ffc993] 過去・現在の自分自身の振り返り
****** ビジネススキル
******* PDSA サイクル
******* 情報整理スキル
******** KJ 法
******** ロジックツリー
******** マインドマップ
******** その他のマッピング分析技法
******** レジュメ構成能力
******** ノート・メモ術
********* バレットジャーナル
********* その他
******** プレゼンテーション術
********* スピーチ
********* ライトニングトーク
******** 情報機器活用術
********* スプレッドシート
********* ワードプロセッサ
********* プレゼンテーション
********* テキストエディタ
********* HTML、CSS、JavaScript、TypeScript
********* PlantUML、Graphviz、MermaidJS、D2、etc...
********* その他
****** 講演やライトニングトークを想定したレジュメ作成


*****[#orange] 自分に合った方法を

@endwbs
